
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres

development:
  <<: *default
  database: ticket_provider_development


test:
  <<: *default
  database: ticket_provider_test

production:
  url: <%= ENV['DATABASE_URL'] %>
